/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_appdevzhang_ndktest_NDKTest */

#ifndef _Included_com_appdevzhang_ndktest_NDKTest
#define _Included_com_appdevzhang_ndktest_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_appdevzhang_ndktest_NDKTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_appdevzhang_ndktest_NDKTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
